### ISSUE TITLE
"Request textDocument/codeLens failed."

### ISSUE THREAD

**Issue by samuela** [DafnyVSCode/Dafny-VSCode#44]
```
[Error - 4:36:48 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
    at Object.dispose (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-languageclient/lib/client.js:57:35)
    at DafnyLanguageClient.handleConnectionClosed (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
    at DafnyLanguageClient.handleConnectionClosed (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-languageclient/lib/main.js:106:15)
    at closeHandler (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
    at CallbackList.invoke (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at closeHandler (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
    at CallbackList.invoke (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at IPCMessageReader.AbstractMessageReader.fireClose (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-jsonrpc/lib/messageReader.js:135:27)
    at ChildProcess.<anonymous> (/Users/skainswo/.vscode-insiders/extensions/correctnesslab.dafny-vscode-0.16.0/node_modules/vscode-jsonrpc/lib/messageReader.js:253:61)
    at ChildProcess.emit (events.js:187:15)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
```

I'm on macOS 10.14.2, VSCode Version 1.33.0-insider (1.33.0-insider), and correctnesslab.dafny-vscode 0.16.0.

**Comment by fabianhauser** [comment]
Thanks for reporting this issue @samuela. Can you give any details under which circumstances/actions the error happened?

**Comment by samuela** [comment]
@fabianhauser Unfortunately I'm not exactly sure when/how this error popped up.

**Comment by DXCanas** [comment]
Getting this same error - VSCode installed on Windows and accessing another machine using the Remote-SSH package. 

Version 2.7 of the extension is installed on the target machine.
