### ISSUE TITLE
Offline install // No network install 

### ISSUE THREAD

**Issue by reisier** [DafnyVSCode/Dafny-VSCode#54]
When trying to install extension offline without network, always fails!
OUTPUT
============================
{ Error: connect ETIMEDOUT 140.82.118.5:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '140.82.118.5',
  port: 443 }
{ Error: connect ETIMEDOUT 140.82.118.5:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '140.82.118.5',
  port: 443 }
errrroooorrr: Error: connect ETIMEDOUT 140.82.118.5:443

**Comment by fabianhauser** [comment]
Hi @reisier 

When exactly does this message appear? During the plugin installation or when you open the first Dafny file?

Thanks,
Fabian

**Comment by reisier** [comment]
Hello, It's when opening the first dafny file.

**Comment by fabianhauser** [comment]
On the first execution, the extension tries to download the newest Dafny Version; the client should handle that gracefully, which does not seem to be the case...
